In [3]:
import numpy as np

loaded_data = np.loadtxt('./exam-score.csv', delimiter=',', dtype=np.float32)

#x_data = loaded_data[ :, 0:-1]
#t_data = loaded_data[ :, [-1]]
x_data = loaded_data[ :, 0:3]
t_data = loaded_data[ :, 3]

print(x_data)
print(t_data)

# 데이터 차원 및 shape 확인
print("x_data.ndim = ", x_data.ndim, ", x_data.shape = ", x_data.shape)
print("t_data.ndim = ", t_data.ndim, ", t_data.shape = ", t_data.shape) 

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
[152. 185. 180. 196. 142. 101. 149. 115. 175. 164. 141. 141. 184. 152.
 148. 192. 147. 183. 177. 159. 177. 175. 175. 149. 192.]
x_data.ndim =  2 , x_data.shape =  (25, 3)
t_data.ndim =  1 , t_data.shape =  (25,)


In [4]:
W = np.random.rand(3,1)  # 3X1 행렬
b = np.random.rand(1)  
print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.19949623]
 [0.44487177]
 [0.17734681]] , W.shape =  (3, 1) , b =  [0.04068] , b.shape =  (1,)


In [5]:
def loss_func(x, t):
    y = np.dot(x,W) + b
    
    return ( np.sum( (t - y)**2 ) ) / ( len(x) )

In [7]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

In [8]:
# 손실함수 값 계산 함수
# 입력변수 x, t : numpy type
def error_val(x, t):
    y = np.dot(x,W) + b
    
    return ( np.sum( (t - y)**2 ) ) / ( len(x) )

# 학습을 마친 후, 임의의 데이터에 대해 미래 값 예측 함수
# 입력변수 x : numpy type
def predict(x):
    y = np.dot(x,W) + b
    
    return y

In [9]:
learning_rate = 1e-5  # 1e-2, 1e-3 은 손실함수 값 발산

f = lambda x : loss_func(x_data,t_data)

print("Initial error value = ", error_val(x_data, t_data), "Initial W = ", W, "\n", ", b = ", b )

for step in  range(10001):  
    
    W -= learning_rate * numerical_derivative(f, W)
    
    b -= learning_rate * numerical_derivative(f, b)
    
    if (step % 400 == 0):
        print("step = ", step, "error value = ", error_val(x_data, t_data), "W = ", W, ", b = ",b )

Initial error value =  248578.745214685 Initial W =  [[0.19949623]
 [0.44487177]
 [0.17734681]] 
 , b =  [0.04068]
step =  0 error value =  17149149.35240896 W =  [[3.95514191]
 [4.21946537]
 [4.05487762]] , b =  [-0.36750482]
step =  400 error value =  1.0998077846402751e+32 W =  [[-1.32750070e+13]
 [ 6.88006121e+11]
 [-1.32764739e+13]] , b =  [1.34453886e+08]
step =  800 error value =  1.0998077846402751e+32 W =  [[-1.32750070e+13]
 [ 6.88006121e+11]
 [-1.32764739e+13]] , b =  [1.34453886e+08]
step =  1200 error value =  1.0998077846402751e+32 W =  [[-1.32750070e+13]
 [ 6.88006121e+11]
 [-1.32764739e+13]] , b =  [1.34453886e+08]
step =  1600 error value =  1.0998077846402751e+32 W =  [[-1.32750070e+13]
 [ 6.88006121e+11]
 [-1.32764739e+13]] , b =  [1.34453886e+08]
step =  2000 error value =  1.0998077846402751e+32 W =  [[-1.32750070e+13]
 [ 6.88006121e+11]
 [-1.32764739e+13]] , b =  [1.34453886e+08]
step =  2400 error value =  1.0998077846402751e+32 W =  [[-1.32750070e+13]
 [ 6.88006

In [10]:
test_data = np.array([100, 98, 81])

predict(test_data) 

array([-2.33547035e+15])